# pywb config file
# ========================================
#

# this is the default; configure to just derrida?
# collections:
#     all: $all


# Settings for each collection
use_js_obj_proxy: true

# Replay content in an iframe
framed_replay: false

# set pywb static prefix to not conflict with archive site static
static_prefix: "pywb_static"


# uncomment and change to set default locale
# default_locale: en

# uncomment to set available locales
# locales:
#  - en
#  - es
